### ISSUE TITLE
Créer une base de joueur personnalisée

### ISSUE THREAD

**Issue by dcpc007** [lucvannier/opengotha#10]
Bonjour,

J'ai vu qu'on peut exporter la liste des participants en csv.
Par contre peut-on gérer une base de joueurs "privée" ou non-officielle pour des tournois internes ?

Actuellement il semble qu'il faille refaire les saisies de chaque joueur à chaque tournoi créé.

**Comment by lucvannier** [comment]
Bonjour dcpc

Les joueurs sont documentés dans le fichier de tournoi (.xml).
Pour intégrer dans un nouveau tournoi les joueurs d'un ancien tournoi, il suffit d'utiliser la fonction d'import (Tournament .. import)

Cordialement
Luc
