### ISSUE TITLE
allow to change first placement criterion

### ISSUE THREAD

**Issue by ygrek** [lucvannier/opengotha#12]
for a small group tournaments with wide range of players strength it may be more fun to use NBW as win criteria, not MMS, but currently it is not possible with macmahon pairing system (first criterion is set to MMS and not allowed to change)

**Comment by lucvannier** [comment]
You will probably be happy with Swiss or Swisscat Systems.
Luc
luc.vannier@gmail.com

**Comment by ygrek** [comment]
Swiss doesn't allow handicap, so yes, I am trying out swisscat now (and making sure everybody goes into same category)
