### ISSUE TITLE
one bug?

### ISSUE THREAD

**Issue by lh1533569752** [lucvannier/opengotha#2]
in Games->results.if we select team presentation,and upper of lower the rounds,then prompting java.lang.NullPointerException . at the som time the show of rounds has some programs,I think we should Catch exception.

**Comment by lucvannier** [comment]
Please send me the xml file ! And the version number.
Thank you !

**Comment by lucvannier** [comment]
Hi lh

2 years later ...

The bug showed up again. Related to a very unusual situation (Player Nr 1
of a team replaced by another player in an other round)

Will be fixed in next release !

Luc

Le mer. 25 oct. 2017 à 13:28, lh1533569752 <notifications@github.com> a
écrit :
