### ISSUE TITLE
Ajout url site web dans le readme

### ISSUE THREAD

**Issue by dcpc007** [lucvannier/opengotha#3]
Bonjour / Hi

ça serait pratique de mettre le lien vers le site web et le téléchargement dans le readme.
Bon j'ai trouvé avec google quand même :)

PS : Merci pour l'appli vais tester ça pour un cas particulier, organiser des mini tournois rapides de tennis de table avec ajustement auto de niveau !

**Comment by lucvannier** [comment]
Bonjour

Merci de votre suggestion !
En fait, les gens trouvent OpenGotha via le site (et éventuellement via un moteur de recherche). Comme vous avez fait, d'ailleurs.

Bons tests sur vos mini tournois.
