### ISSUE TITLE
Ajout dossier parent dans le zip de livraison

### ISSUE THREAD

**Issue by dcpc007** [lucvannier/opengotha#4]
Bonjour,

Il serait pratique d'ajouter un dossier parent (root) initial dans le zip de l'installation, pour éviter les erreurs du genre dézipper l'archive en oubliant de préciser un sous-dossier, et du coup tout avoir en vrac mélangé avec les autres dossiers (ouverture du matin = viens de me faire avoir :) )

PS : Comment est généré le zip ? y a-t-il une intégration continue par exemple ?

**Comment by lucvannier** [comment]
Les outils de zip/unzip font ça très bien ! En cas d'erreur d'inattention, refaire la manip et indiquer un répertoire cible.

J'envisage de proposer un .exe, ce qui permettra de simplifier au maximum le processus.
Bons tournois !
