### ISSUE TITLE
Ajustement au système "ELO" pour le tennis de table

### ISSUE THREAD

**Issue by dcpc007** [lucvannier/opengotha#5]
Bonjour

J'aimerais utiliser votre application pour gérer des petits tournois de tennis de tables, sans devoir faire manuellement tous les calculs parfois compliqués pour gérer les niveaux des joueurs.
Par contre je découvre le logiciel et n'ai que peu d'expériences pour le configurer, si vous auriez une idée de comment configurer les joueurs avec une équivalence de rating/grade ou rank, ça m'aiderait bien :)

Au tennis de table, les classements sont sur un système de points type ELO.
Les débutants sont à 500, à 1200 on est un très bon joueur déjà et à 2000 on arrive dans les nationaux, 2500 on est 100ème français, et 3500 n°1 français.
Souvent on définit des classes par centaines pour définir un niveau (les 5, les 6, les 7,...), et 250 points d'écart ça devient une grosse perf (ou contre), 400 points d'écart en cas de défaite vous ne perdez plus de point de classement.

Pour moi je devrais sûrement gérer des cas de 500 à 1300 voir 1500 (pas un gros club :) )

J'hésite encore entre swiss et mcMahon.
- swiss permet de jouer tlm, mais les 2 premiers tours sont déséquilibrés et limite inutile car fait jouer les plus forts contre moins forts .... et (avantage ou inconvénient) les classements du milieu semblent plutôt aléatoires voir contrôlables par les joueurs (technique du sous-marin)
- mcmahon j'ai un peu peur que ça fige les gens dans leur classement initial avec très peu de chance de faire un bon classement au final, donc peu de surprises.
Je vais essayer de faire des tests, avec même le cas d'un joueur faible qui fait 5 perfs de suite par ex pour voir.

**Comment by dcpc007** [comment]
Si je ne prévois aucun très haut niveau, j'ai fait une feuille d'équivalence FFTT <--> Go en prenant des paliers de 50 points : 
- 500 -> 30k
- 550 -> 29k
- 600 -> 28k
- 1950 -> 1k
- 2000 -> 1d
- 2400 -> 9d
ça couvre presque tout le monde, même si tout en haut dans les 9d en fait ça couvre des très gros écarts de niveau (quasi aucune chance entre un 150 et un 80, et le 80 pareil contre un 40 par ex...)

**Comment by dcpc007** [comment]
Premier test ce soir si j'ai assez de monde '(pour le moment que 5 joueurs :) )

**Comment by lucvannier** [comment]
Bonjour

Je pense que vous avez bien compris le fonctionnement des systèmes suisses
et MacMahon.
A vous, en effet de trouver l'équivalence ELO Tennis de table <-> Niveaux
en kyu et Dan qui réalise le meilleur compromis "Parties intéressantes" vs
"Tout le monde a sa chance"

Bons tournois !

Luc

**Comment by dcpc007** [comment]
Merci beaucoup, 

Première utilisation officielle en décembre :)
Je verrais avec ces retours les avis sur les 2 possibilités, mais apporter ce type de système qui n'est pas classique "déroute" un peu dans les premiers retours :)

Le classement semble se tenir pour l'équivalence, je ne peux pas prendre en compte les plus hauts classements mais en fait ils seraient associés plus à des 1p à 9p à ce niveau ce ne sont plus des amateurs en général et ils ne viendront pas à ces compèt amateurs :)

Les premières simulations et essais semblent ok.
