### ISSUE TITLE
Calculer le nombre de rounds (suisse)

### ISSUE THREAD

**Issue by dcpc007** [lucvannier/opengotha#7]
J'essaye de savoir comment définir le nombre de round minimal pour des petits tournois (ex : 10-20-30 joueurs).

J'ai trouvé ça sur le net mais pas sûr de la valeur : 
1 rd, 2 players
2 rds, 4 players
3 rds, 8 players
4 rds, 16 players
5 rds, 32 players
6 rds, 64 players

ça parle aussi de fonction type log2(nb_players), bon, ça date pour moi ça

**Comment by lucvannier** [comment]
Les nombres de rondes que vous mentionnez sont des minimums, en effet. Quoi dire de plus ?

**Comment by dcpc007** [comment]
ok, donc si j'ai 24 personnes, je dois prendre mini 4 rondes ou 5 rondes du coup ?
ou dit autrement : 
1°) il faut 3 rondes minimum pour 8 à 15 joueurs ou
2°) il faut 3 rondes minimum pour 5 à 8 joueurs ?

(Comme on a pas bcp de place pour les tables, je retente bientôt un autre test avec plus de monde pour être obligé de faire une ronde en 2 passes : les 12 premiers joueurs puis les 2 à 12 suivants, et ensuite je calcule le résultat.
Je dois prévoir les durées estimée car en général on a une heure limite pour la salle. Je peux faire jouer sur des paramètres comme le nb de sets gagnants : 2 ou 3 par ex, et même voir par ex si je peux rajouter une ronde à la fin s'il reste du temps par ex)

**Comment by lucvannier** [comment]
Arrondir au nombre supérieur.

Pour être précis, il existe des systèmes (Suisse accéléré) pour gérer un tournoi avec un nombre de rondes inférieur. Mais bon, le + simple est de respecter cette règle nb_rondes >= log2(nb_players)

Pour les autres détails d'organisation, je vous conseille de vous rapprocher d'un organisateur expérimenté.
