### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by colingrierson** [lucvannier/opengotha#8]
I have a high resolution screen and on this OpenGotha is tiny, so small it is unusable because I cannot read the text. Other than changing my screen resolution is there any way to make OpenGotha use a larger font?

Thanks, Colin

**Comment by lucvannier** [comment]
No, so far, no ! What OS do you use ?

Le dim. 9 sept. 2018 à 11:52, colingrierson <notifications@github.com> a
écrit :

**Comment by lucvannier** [comment]
Colingrierson, you have a zoom function in Windows  ([Touche Windows] + [Touche +])
